In [31]:
#Q1-->valid sudoku
import numpy as np

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
sum1=s.sum(axis=0)
sum2=s.sum(axis=1)
c=0
for i in sum1:
    if (i!=45):
        c=c+1
        break
for i in sum2:
    if (i!=45):
        c=c+1
        break
for i in range(0,9,3):
    for j in range(0,9,3):
        if (s[i:i+3,j:j+3].sum()!=45):
            c=c+1
            break
if(c!=0):
    print("invalid sudoku")
else:
    print("valid sudoku")

valid sudoku


In [62]:
#Q2-->DATA BASED
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])
#avg of age
print(data[:,0].mean())
#maths marks of all students
print(data[:,1])
#highest science marks
print(data[:,2].max())
#who scored more than 90 in math
print(data[data[:,1]>90])
#increase maths marks by 5
data[:,1] =data[:,1]+5
print(data)
#students younger than 19
print(data[data[:,0]<19])
#column wise subject mean
mean=data.mean(axis=0)
print(mean[1:3])
#who scored atleast 80 in both the subjects
print(data[(data[:,1]>=80) & (data[:,2]>=80)])
#replace all science marks <75 with 0.
data[:,2][data[:,2]<75]=0
print(data)

18.4
[85 92 76 65 90]
95
[[19 92 88]]
[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]
[[18 90 78]
 [17 81 95]
 [18 70 70]]
[86.6 83.2]
[[19 97 88]
 [17 81 95]
 [20 95 85]]
[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
